import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calendarBP,overlaps,siteStatus,countyClass,project} from '../lib/evidence.ts';
const d=JSON.parse(fs.readFileSync(new URL('../public/data/evidence.json',import.meta.url)));
const geo=JSON.parse(fs.readFileSync(new URL('../public/data/counties.geojson',import.meta.url)));
const empty={...d,cores:[],landscape:[],sites:[]};
test('Historical dates respect no year zero and BP reference',()=>{assert.equal(calendarBP(1,'BCE'),1950);assert.equal(calendarBP(1,'CE'),1949);assert.equal(calendarBP(1950,'CE'),0);assert.throws(()=>calendarBP(0,'CE'))});
test('Inclusive overlap, missing ages, invalid ranges',()=>{for(const x of [2000,2500])assert.equal(overlaps({oldestBP:x,youngestBP:x},2000,2500),true);for(const x of [1999,2501])assert.equal(overlaps({oldestBP:x,youngestBP:x},2000,2500),false);assert.equal(overlaps({oldestBP:null,youngestBP:2000},2000,2500),false);assert.equal(overlaps({oldestBP:1900,youngestBP:2200},2000,2500),false)});
test('Disjoint dates do not fill a gap; unresolved period remains unresolved',()=>{const s={periods:[{oldestBP:1500,youngestBP:1000},{oldestBP:3500,youngestBP:3000}]};assert.equal(siteStatus(s,2000,2500),'outside');s.periods.push({oldestBP:null,youngestBP:null});assert.equal(siteStatus(s,2000,2500),'undated')});
test('Real sites change with time while geological inventory stays stable',()=>{assert.notEqual(d.sites.filter(s=>siteStatus(s,1500,2000)==='overlap').length,d.sites.filter(s=>siteStatus(s,10000,10500)==='overlap').length);for(const f of geo.features)assert.equal(countyClass(f.properties.id,'coverage',d,0,500),countyClass(f.properties.id,'coverage',d,15000,15500));});
test('Undated cores cannot colour historical landscape',()=>{assert.equal(d.landscape.length,0);for(const c of d.cores)assert.equal(countyClass(c.countyId,'landscape',d,2000,2500),'unknown')});
test('Provisional-only and mixed core counties classify deterministically',()=>{assert.equal(countyClass('39143','coverage',d,2000,2500),'provisional');const a={...empty,cores:[{id:'test-a',countyId:'x',location_status:'verified'},{id:'C03051',countyId:'x'}]};assert.equal(countyClass('x','coverage',a,0,500),'available');assert.equal(countyClass('z','coverage',a,0,500),'none')});
test('Temporal evidence precedence and exclusion',()=>{const rec={id:'t',countyId:'x',oldestBP:2500,youngestBP:2000,spatialSupport:'local',status:'interpreted'};const a={...empty,landscape:[rec]};assert.equal(countyClass('x','landscape',a,2000,2500),'local');assert.equal(countyClass('x','landscape',a,3000,3500),'unknown');a.landscape.push({...rec,id:'r',spatialSupport:'regional'});assert.equal(countyClass('x','landscape',a,2000,2500),'regional');a.landscape.push({...rec,id:'c',status:'conflicting'});assert.equal(countyClass('x','landscape',a,2000,2500),'conflicting')});
test('County membership, source joins and unique IDs',()=>{assert.equal(geo.features.length,171);const ids=new Set(geo.features.map(f=>f.properties.id));assert.equal(ids.size,171);assert.equal([...ids].filter(i=>i.startsWith('26')).length,83);assert.equal([...ids].filter(i=>i.startsWith('39')).length,88);const sources=new Set(d.sources.map(s=>s.id));assert.equal(sources.size,d.sources.length);for(const x of [...d.cores,...d.sites,...d.leads,...d.landscape]){assert.ok(ids.has(x.countyId),x.id);for(const s of x.sourceIds||[])assert.ok(sources.has(s),s);}for(const s of d.sites)for(const p of s.periods){assert.ok(sources.has(p.sourceId));assert.ok(p.oldestBP>=p.youngestBP)}});
function inRing(p,r){let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const [xi,yi]=r[i],[xj,yj]=r[j];if((yi>p[1])!==(yj>p[1])&&p[0]<(xj-xi)*(p[1]-yi)/(yj-yi)+xi)inside=!inside;}return inside;}
function contains(g,p){const polys=g.type==='Polygon'?[g.coordinates]:g.coordinates;return polys.some(poly=>inRing(p,poly[0])&&!poly.slice(1).some(h=>inRing(p,h)));}
test('Public site reference points fall inside assigned county; county-only Norton has no fabricated location',()=>{for(const s of d.sites){if(s.latitude===null){assert.equal(s.longitude,null);continue}const f=geo.features.find(f=>f.properties.id===s.countyId);assert.ok(contains(f.geometry,[s.longitude,s.latitude]),s.id);}assert.equal(d.sites.find(s=>s.name.includes('Norton')).latitude,null)});
test('Inherited intervals, known depths and source flags retained',()=>{assert.equal(d.cores.length,7);assert.equal(d.cores.reduce((a,c)=>a+c.intervals.length,0),226);assert.equal(d.cores.find(c=>c.id==='C03082').depth_ft,24.5);assert.ok(d.cores.find(c=>c.id==='C03082').quality_flags.some(x=>x.includes('52')));assert.ok(d.cores.find(c=>c.id==='C03051').quality_flags.length>0);for(const c of d.cores)for(const p of c.intervals)assert.ok(p.bottom_ft>p.top_ft,`${c.id}: ${p.top_ft}`)});
test('Research lead retains alternative, blockers and provenance',()=>{const l=d.leads.find(l=>l.coreId==='C03082');assert.ok(l.alternative);assert.ok(l.nextCheck);assert.ok(l.blockers.includes('Numerical age'));assert.ok(l.sourceIds.includes('geo-C03082'))});
test('Georeferenced relief and map projection share an extent',()=>{assert.deepEqual(project(-10500000/6378137*180/Math.PI,Math.atan(Math.sinh(6200000/6378137))*180/Math.PI).map(Math.round),[0,0]);const t=JSON.parse(fs.readFileSync(new URL('../public/data/terrain.json',import.meta.url)));assert.equal(t.extent.xmin,-10500000);assert.equal(t.extent.ymax,6200000)});
